### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by Benjamin-Walker** [Benjamin-Walker/log-neural-cdes#1]
This is going to be a tracker of everything that needs to be implemented into this repository. 

## Datasets
- [x] Find additional datasets
#### Raw Data
- [x] UEA multivariate time-series datasets
- [x] PPG-DaLiA dataset
- [x] Toy Dataset
#### Processed Data
- [x] UEA multivariate time-series datasets
- [x] PPG-DaLiA dataset
- [x] Toy Dataset

## Dataloaders
- [x] Original Signal
- [x] Log signature

## Baseline Models
- [x] RNN
- [x] LSTM
- [x] LRU
- [x] Neural CDE
- [x] Neural RDE
- [x] S5 

## Log Neural CDEs
- [x] Basic Implementation
- [x] Hall Basis with Signax
